--
-- PostgreSQL database dump
--

-- Dumped from database version 14.4 (Debian 14.4-1.pgdg110+1)
-- Dumped by pg_dump version 14.4 (Debian 14.4-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    date date,
    paid boolean,
    "time" time without time zone,
    client_id bigint,
    specialist_id bigint
);


ALTER TABLE public.appointments OWNER TO postgres;

--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    health_insurance_policy_number character varying(255),
    name character varying(255),
    patronymic character varying(255),
    surname character varying(255),
    phone_number character varying(255)
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);


--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.hibernate_sequence OWNER TO postgres;

--
-- Name: hibernate_sequences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hibernate_sequences (
    sequence_name character varying(255) NOT NULL,
    next_val bigint
);


ALTER TABLE public.hibernate_sequences OWNER TO postgres;

--
-- Name: medical_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medical_service (
    id bigint NOT NULL,
    duration time without time zone,
    name character varying(255),
    price integer
);


ALTER TABLE public.medical_service OWNER TO postgres;

--
-- Name: medical_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medical_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medical_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: specialists; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.specialists (
    id bigint NOT NULL,
    name character varying(255),
    patronymic character varying(255),
    room integer,
    surname character varying(255),
    medical_service_id bigint,
    phone_number character varying(255)
);


ALTER TABLE public.specialists OWNER TO postgres;

--
-- Name: specialists_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.specialists ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.specialists_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_roles (
    id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.user_roles OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255),
    phone_number character varying(255)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 2147483647
    CACHE 1
);


--
-- Name: users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_roles (
    users_id bigint NOT NULL,
    roles_id bigint NOT NULL
);


ALTER TABLE public.users_roles OWNER TO postgres;

--
-- Name: work_day_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.work_day_entity (
    id bigint NOT NULL,
    specialist_appointment_end time without time zone,
    specialist_appointment_start time without time zone,
    work_day integer,
    specialist_id bigint,
    day_of_week integer
);


ALTER TABLE public.work_day_entity OWNER TO postgres;

--
-- Data for Name: appointments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments (id, date, paid, "time", client_id, specialist_id) FROM stdin;
1	2022-07-16	f	16:00:00	\N	4
2	2022-07-16	f	16:45:00	\N	4
3	2022-07-16	f	17:30:00	\N	4
4	2022-07-16	f	18:15:00	\N	4
5	2022-07-16	f	19:00:00	\N	4
6	2022-07-16	f	19:45:00	\N	4
7	2022-07-16	f	12:00:00	\N	2
8	2022-07-16	f	12:25:00	\N	2
9	2022-07-16	f	12:50:00	\N	2
10	2022-07-16	f	13:15:00	\N	2
11	2022-07-16	f	13:40:00	\N	2
12	2022-07-16	f	14:05:00	\N	2
13	2022-07-16	f	14:30:00	\N	2
14	2022-07-16	f	14:55:00	\N	2
15	2022-07-16	f	15:20:00	\N	2
16	2022-07-16	f	15:45:00	\N	2
17	2022-07-17	f	10:00:00	\N	4
18	2022-07-17	f	10:45:00	\N	4
19	2022-07-17	f	11:30:00	\N	4
20	2022-07-17	f	12:15:00	\N	4
21	2022-07-17	f	13:00:00	\N	4
22	2022-07-17	f	13:45:00	\N	4
23	2022-07-17	f	08:00:00	\N	1
24	2022-07-17	f	08:30:00	\N	1
25	2022-07-17	f	09:00:00	\N	1
26	2022-07-17	f	09:30:00	\N	1
27	2022-07-17	f	10:00:00	\N	1
28	2022-07-17	f	10:30:00	\N	1
29	2022-07-17	f	11:00:00	\N	1
30	2022-07-17	f	11:30:00	\N	1
35	2022-07-19	f	18:00:00	\N	5
36	2022-07-19	f	18:30:00	\N	5
37	2022-07-19	f	19:00:00	\N	5
38	2022-07-19	f	19:30:00	\N	5
45	2022-07-19	f	14:30:00	\N	3
46	2022-07-19	f	14:55:00	\N	3
47	2022-07-19	f	15:20:00	\N	3
48	2022-07-19	f	15:45:00	\N	3
50	2022-07-19	f	08:30:00	\N	1
51	2022-07-19	f	09:00:00	\N	1
52	2022-07-19	f	09:30:00	\N	1
53	2022-07-19	f	10:00:00	\N	1
54	2022-07-19	f	10:30:00	\N	1
55	2022-07-19	f	11:00:00	\N	1
56	2022-07-19	f	11:30:00	\N	1
62	2022-07-20	f	09:15:00	\N	6
63	2022-07-20	f	09:30:00	\N	6
64	2022-07-20	f	09:45:00	\N	6
66	2022-07-20	f	10:15:00	\N	6
67	2022-07-20	f	10:30:00	\N	6
68	2022-07-20	f	10:45:00	\N	6
69	2022-07-20	f	11:00:00	\N	6
70	2022-07-20	f	11:15:00	\N	6
71	2022-07-20	f	11:30:00	\N	6
72	2022-07-20	f	11:45:00	\N	6
76	2022-07-20	f	18:15:00	\N	4
78	2022-07-20	f	19:45:00	\N	4
80	2022-07-20	f	14:25:00	\N	2
81	2022-07-20	f	14:50:00	\N	2
82	2022-07-20	f	15:15:00	\N	2
83	2022-07-20	f	15:40:00	\N	2
84	2022-07-21	f	08:00:00	\N	5
85	2022-07-21	f	08:30:00	\N	5
86	2022-07-21	f	09:00:00	\N	5
87	2022-07-21	f	09:30:00	\N	5
88	2022-07-21	f	10:00:00	\N	5
89	2022-07-21	f	10:30:00	\N	5
90	2022-07-21	f	11:00:00	\N	5
92	2022-07-21	f	17:25:00	\N	3
93	2022-07-21	f	17:50:00	\N	3
94	2022-07-21	f	18:15:00	\N	3
95	2022-07-21	f	18:40:00	\N	3
96	2022-07-21	f	10:00:00	\N	2
97	2022-07-21	f	10:25:00	\N	2
98	2022-07-21	f	10:50:00	\N	2
99	2022-07-21	f	11:15:00	\N	2
100	2022-07-21	f	11:40:00	\N	2
101	2022-07-21	f	12:05:00	\N	2
102	2022-07-21	f	12:30:00	\N	2
103	2022-07-21	f	12:55:00	\N	2
104	2022-07-21	f	13:20:00	\N	2
105	2022-07-21	f	13:45:00	\N	2
108	2022-07-22	f	18:00:00	\N	6
109	2022-07-22	f	18:15:00	\N	6
110	2022-07-22	f	18:30:00	\N	6
111	2022-07-22	f	18:45:00	\N	6
112	2022-07-22	f	19:00:00	\N	6
113	2022-07-22	f	19:15:00	\N	6
117	2022-07-22	f	13:45:00	\N	4
118	2022-07-22	f	14:30:00	\N	4
119	2022-07-22	f	15:15:00	\N	4
120	2022-07-23	f	16:00:00	\N	4
121	2022-07-23	f	16:45:00	\N	4
122	2022-07-23	f	17:30:00	\N	4
123	2022-07-23	f	18:15:00	\N	4
124	2022-07-23	f	19:00:00	\N	4
125	2022-07-23	f	19:45:00	\N	4
128	2022-07-23	f	12:50:00	\N	2
129	2022-07-23	f	13:15:00	\N	2
130	2022-07-23	f	13:40:00	\N	2
131	2022-07-23	f	14:05:00	\N	2
132	2022-07-23	f	14:30:00	\N	2
133	2022-07-23	f	14:55:00	\N	2
134	2022-07-23	f	15:20:00	\N	2
135	2022-07-23	f	15:45:00	\N	2
136	2022-07-24	f	10:00:00	\N	4
43	2022-07-19	f	13:40:00	\N	3
39	2022-07-19	t	12:00:00	7	3
41	2022-07-19	t	12:50:00	7	3
40	2022-07-19	t	12:25:00	7	3
106	2022-07-22	f	17:30:00	\N	6
34	2022-07-19	f	17:30:00	\N	5
73	2022-07-20	f	16:00:00	\N	4
42	2022-07-19	f	13:15:00	\N	3
44	2022-07-19	f	14:05:00	\N	3
116	2022-07-22	f	13:00:00	\N	4
115	2022-07-22	f	12:15:00	\N	4
79	2022-07-20	f	14:00:00	\N	2
107	2022-07-22	f	17:45:00	\N	6
49	2022-07-19	f	08:00:00	\N	1
57	2022-07-20	f	08:00:00	\N	6
60	2022-07-20	f	08:45:00	\N	6
61	2022-07-20	f	09:00:00	\N	6
91	2022-07-21	t	17:00:00	2	3
74	2022-07-20	f	16:45:00	3	4
75	2022-07-20	f	17:30:00	3	4
77	2022-07-20	f	19:00:00	3	4
126	2022-07-23	f	12:00:00	\N	2
58	2022-07-20	f	08:15:00	3	6
127	2022-07-23	t	12:25:00	2	2
137	2022-07-24	f	10:45:00	\N	4
138	2022-07-24	f	11:30:00	\N	4
139	2022-07-24	f	12:15:00	\N	4
140	2022-07-24	f	13:00:00	\N	4
141	2022-07-24	f	13:45:00	\N	4
151	2022-07-26	f	16:30:00	\N	5
152	2022-07-26	f	17:00:00	\N	5
153	2022-07-26	f	17:30:00	\N	5
154	2022-07-26	f	18:00:00	\N	5
155	2022-07-26	f	18:30:00	\N	5
156	2022-07-26	f	19:00:00	\N	5
157	2022-07-26	f	19:30:00	\N	5
159	2022-07-26	f	12:25:00	\N	3
160	2022-07-26	f	12:50:00	\N	3
161	2022-07-26	f	13:15:00	\N	3
162	2022-07-26	f	13:40:00	\N	3
163	2022-07-26	f	14:05:00	\N	3
164	2022-07-26	f	14:30:00	\N	3
165	2022-07-26	f	14:55:00	\N	3
166	2022-07-26	f	15:20:00	\N	3
167	2022-07-26	f	15:45:00	\N	3
168	2022-07-26	f	08:00:00	\N	1
169	2022-07-26	f	08:30:00	\N	1
170	2022-07-26	f	09:00:00	\N	1
171	2022-07-26	f	09:30:00	\N	1
172	2022-07-26	f	10:00:00	\N	1
173	2022-07-26	f	10:30:00	\N	1
174	2022-07-26	f	11:00:00	\N	1
175	2022-07-26	f	11:30:00	\N	1
176	2022-07-27	f	08:00:00	\N	6
177	2022-07-27	f	08:15:00	\N	6
178	2022-07-27	f	08:30:00	\N	6
179	2022-07-27	f	08:45:00	\N	6
180	2022-07-27	f	09:00:00	\N	6
181	2022-07-27	f	09:15:00	\N	6
182	2022-07-27	f	09:30:00	\N	6
183	2022-07-27	f	09:45:00	\N	6
184	2022-07-27	f	10:00:00	\N	6
185	2022-07-27	f	10:15:00	\N	6
186	2022-07-27	f	10:30:00	\N	6
187	2022-07-27	f	10:45:00	\N	6
188	2022-07-27	f	11:00:00	\N	6
189	2022-07-27	f	11:15:00	\N	6
190	2022-07-27	f	11:30:00	\N	6
191	2022-07-27	f	11:45:00	\N	6
192	2022-07-27	f	16:00:00	\N	4
193	2022-07-27	f	16:45:00	\N	4
194	2022-07-27	f	17:30:00	\N	4
195	2022-07-27	f	18:15:00	\N	4
196	2022-07-27	f	19:00:00	\N	4
197	2022-07-27	f	19:45:00	\N	4
198	2022-07-27	f	14:00:00	\N	2
199	2022-07-27	f	14:25:00	\N	2
200	2022-07-27	f	14:50:00	\N	2
201	2022-07-27	f	15:15:00	\N	2
202	2022-07-27	f	15:40:00	\N	2
203	2022-07-28	f	08:00:00	\N	5
204	2022-07-28	f	08:30:00	\N	5
205	2022-07-28	f	09:00:00	\N	5
206	2022-07-28	f	09:30:00	\N	5
207	2022-07-28	f	10:00:00	\N	5
208	2022-07-28	f	10:30:00	\N	5
209	2022-07-28	f	11:00:00	\N	5
210	2022-07-28	f	17:00:00	\N	3
211	2022-07-28	f	17:25:00	\N	3
212	2022-07-28	f	17:50:00	\N	3
213	2022-07-28	f	18:15:00	\N	3
214	2022-07-28	f	18:40:00	\N	3
215	2022-07-28	f	10:00:00	\N	2
216	2022-07-28	f	10:25:00	\N	2
217	2022-07-28	f	10:50:00	\N	2
218	2022-07-28	f	11:15:00	\N	2
219	2022-07-28	f	11:40:00	\N	2
220	2022-07-28	f	12:05:00	\N	2
221	2022-07-28	f	12:30:00	\N	2
222	2022-07-28	f	12:55:00	\N	2
223	2022-07-28	f	13:20:00	\N	2
224	2022-07-28	f	13:45:00	\N	2
225	2022-07-29	f	17:30:00	\N	6
226	2022-07-29	f	17:45:00	\N	6
227	2022-07-29	f	18:00:00	\N	6
228	2022-07-29	f	18:15:00	\N	6
229	2022-07-29	f	18:30:00	\N	6
230	2022-07-29	f	18:45:00	\N	6
231	2022-07-29	f	19:00:00	\N	6
232	2022-07-29	f	19:15:00	\N	6
233	2022-07-29	f	11:30:00	\N	4
234	2022-07-29	f	12:15:00	\N	4
235	2022-07-29	f	13:00:00	\N	4
236	2022-07-29	f	13:45:00	\N	4
237	2022-07-29	f	14:30:00	\N	4
238	2022-07-29	f	15:15:00	\N	4
31	2022-07-19	f	16:00:00	\N	5
114	2022-07-22	f	11:30:00	\N	4
32	2022-07-19	f	16:30:00	\N	5
142	2022-07-24	t	08:00:00	2	1
150	2022-07-26	t	16:00:00	2	5
59	2022-07-20	t	08:30:00	2	6
158	2022-07-26	t	12:00:00	2	3
33	2022-07-19	f	17:00:00	3	5
145	2022-07-24	t	09:30:00	2	1
146	2022-07-24	f	10:00:00	3	1
148	2022-07-24	f	11:00:00	3	1
147	2022-07-24	f	10:30:00	3	1
149	2022-07-24	t	11:30:00	2	1
144	2022-07-24	f	09:00:00	\N	1
143	2022-07-24	f	08:30:00	\N	1
\.


--
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (id, health_insurance_policy_number, name, patronymic, surname, phone_number) FROM stdin;
3	345235	Павел	Валерьевич	Ховяков	\N
4	4564879	Андрей	Владимирович	Андреев	\N
5	4689732	Андрей	Александрович	Смирнов	\N
2	456789456	Олег	Анатольевич	Иванов	9185895633
6	3791456789	Валерий	Михайлович	Авдяков	9183791456
7	4567891325	Александр	Николаевич	Шишкин	9517539512
11	1234567	Ричард	Филлипс	Фейнман	9955561327
\.


--
-- Data for Name: hibernate_sequences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.hibernate_sequences (sequence_name, next_val) FROM stdin;
default	11
\.


--
-- Data for Name: medical_service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medical_service (id, duration, name, price) FROM stdin;
1	00:30:00	Терапевт	1000
2	00:25:00	Окулист	1500
3	00:45:00	Хирург	1200
4	00:30:00	Кардиолог	1000
5	00:15:00	Рентгенолог	500
\.


--
-- Data for Name: specialists; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.specialists (id, name, patronymic, room, surname, medical_service_id, phone_number) FROM stdin;
1	Станислав	Владимирович	44	Петухов	1	\N
5	Владислав	Анатольевич	57	Кулешов	4	\N
4	Александр	Иванович	35	Петров	3	\N
3	Иван	Васильевич	22	Меняетпрофессию	2	\N
2	Евгений	Алексеевич	21	Сидоров	2	9887651235
6	Евгения	Владимировна	18	Белоножкова	5	9951597812
\.


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_roles (id, name) FROM stdin;
1	ROLE_USER
2	ROLE_SPEC
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, phone_number) FROM stdin;
2	$2a$10$8ctMUrZVzLp3aqD5wXkTc.VD.JfR4mpDCHkKZbWCJkOZVTKwRz/r2	9185895633
6	$2a$10$aNfb3cjjhrye.seGihatG.QJOZtFbwoVtl4jfxj.e2iPhyXkpehIa	9183791456
7	$2a$10$Mydb0XoHCB3faGdcxOhqfOh.EGepA1X3rLRvykoG17Fe/x76enUnm	9517539512
11	$2a$10$M479Ctvw1wxcKS02TRFboekv4AvcH/R9/Lj5YUFVAzVMng.qNJZ4C	9955561327
12	$2a$12$.rfnUgbjBMw/vksJNNsrqut/uVFGwPZ6lH3dXCBB5swHdkRiw8s8i	9887651235
13	$2a$12$Qm2TvC..LMC8hGIGJcihte6cRkWuJ/SmZLWAh0p9THeXmrnLQajb2	9951597812
\.


--
-- Data for Name: users_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_roles (users_id, roles_id) FROM stdin;
2	1
6	1
7	1
11	1
12	2
13	2
\.


--
-- Data for Name: work_day_entity; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.work_day_entity (id, specialist_appointment_end, specialist_appointment_start, work_day, specialist_id, day_of_week) FROM stdin;
8	19:00:00	17:00:00	3	3	\N
4	16:00:00	14:00:00	2	2	\N
10	15:30:00	11:30:00	4	4	\N
1	12:00:00	08:00:00	1	1	\N
7	14:00:00	10:00:00	3	2	\N
2	16:00:00	12:00:00	1	3	\N
9	11:30:00	08:00:00	3	5	\N
3	20:00:00	16:00:00	1	5	\N
14	12:00:00	08:00:00	6	1	\N
15	14:00:00	10:00:00	6	4	\N
13	20:00:00	16:00:00	5	4	\N
6	12:00:00	08:00:00	2	6	\N
5	20:00:00	16:00:00	2	4	\N
11	19:30:00	17:30:00	4	6	\N
12	16:00:00	12:00:00	5	2	\N
\.


--
-- Name: appointments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_id_seq', 238, true);


--
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_id_seq', 5, true);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.hibernate_sequence', 1, false);


--
-- Name: medical_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medical_service_id_seq', 5, true);


--
-- Name: specialists_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.specialists_id_seq', 6, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 13, true);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: hibernate_sequences hibernate_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hibernate_sequences
    ADD CONSTRAINT hibernate_sequences_pkey PRIMARY KEY (sequence_name);


--
-- Name: medical_service medical_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medical_service
    ADD CONSTRAINT medical_service_pkey PRIMARY KEY (id);


--
-- Name: specialists specialists_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialists
    ADD CONSTRAINT specialists_pkey PRIMARY KEY (id);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_roles users_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_pkey PRIMARY KEY (users_id, roles_id);


--
-- Name: work_day_entity work_day_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_day_entity
    ADD CONSTRAINT work_day_entity_pkey PRIMARY KEY (id);


--
-- Name: clients_phone_number_uindex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX clients_phone_number_uindex ON public.clients USING btree (phone_number);


--
-- Name: users_phone_number_uindex; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_phone_number_uindex ON public.users USING btree (phone_number);


--
-- Name: work_day_entity fkacygnellk27xpag7qf1im18f5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.work_day_entity
    ADD CONSTRAINT fkacygnellk27xpag7qf1im18f5 FOREIGN KEY (specialist_id) REFERENCES public.specialists(id);


--
-- Name: specialists fkexy0649p0ti7lbc19vt25825i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.specialists
    ADD CONSTRAINT fkexy0649p0ti7lbc19vt25825i FOREIGN KEY (medical_service_id) REFERENCES public.medical_service(id);


--
-- Name: appointments fkfbl6cciquyyvv5s1e31qmflkb; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkfbl6cciquyyvv5s1e31qmflkb FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- Name: appointments fkla5m7grca1orgd3e5vipc9jbs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkla5m7grca1orgd3e5vipc9jbs FOREIGN KEY (specialist_id) REFERENCES public.specialists(id);


--
-- Name: users_roles fkml90kef4w2jy7oxyqv742tsfc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkml90kef4w2jy7oxyqv742tsfc FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- Name: users_roles fkr7n16jrocdrem7nca7dasjf12; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT fkr7n16jrocdrem7nca7dasjf12 FOREIGN KEY (roles_id) REFERENCES public.user_roles(id);


--
-- PostgreSQL database dump complete
--

