version: "3"

services:
  bookingsource_main:
    build:
      dockerfile: Dockerfile
      context: '.'
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/booking
      SPRING_THYMELEAF_PREFIX: file:/usr/app/
  postgres:
    build:
      dockerfile: Dockerfile_pg
      context: '.'
    ports:
      - "5433:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local